# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from dcs.group.v0 import group_pb2 as dcs_dot_group_dot_v0_dot_group__pb2


class GroupServiceStub(object):
    """https://wiki.hoggitworld.com/view/DCS_Class_Group
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUnits = channel.unary_unary(
                '/dcs.group.v0.GroupService/GetUnits',
                request_serializer=dcs_dot_group_dot_v0_dot_group__pb2.GetUnitsRequest.SerializeToString,
                response_deserializer=dcs_dot_group_dot_v0_dot_group__pb2.GetUnitsResponse.FromString,
                )


class GroupServiceServicer(object):
    """https://wiki.hoggitworld.com/view/DCS_Class_Group
    """

    def GetUnits(self, request, context):
        """https://wiki.hoggitworld.com/view/DCS_func_getUnits
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GroupServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUnits': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUnits,
                    request_deserializer=dcs_dot_group_dot_v0_dot_group__pb2.GetUnitsRequest.FromString,
                    response_serializer=dcs_dot_group_dot_v0_dot_group__pb2.GetUnitsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dcs.group.v0.GroupService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GroupService(object):
    """https://wiki.hoggitworld.com/view/DCS_Class_Group
    """

    @staticmethod
    def GetUnits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dcs.group.v0.GroupService/GetUnits',
            dcs_dot_group_dot_v0_dot_group__pb2.GetUnitsRequest.SerializeToString,
            dcs_dot_group_dot_v0_dot_group__pb2.GetUnitsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
