# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dcs/group/v0/group.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dcs.common.v0 import common_pb2 as dcs_dot_common_dot_v0_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64\x63s/group/v0/group.proto\x12\x0c\x64\x63s.group.v0\x1a\x1a\x64\x63s/common/v0/common.proto\"E\n\x0fGetUnitsRequest\x12\x12\n\ngroup_name\x18\x01 \x01(\t\x12\x13\n\x06\x61\x63tive\x18\x02 \x01(\x08H\x00\x88\x01\x01\x42\t\n\x07_active\"6\n\x10GetUnitsResponse\x12\"\n\x05units\x18\x01 \x03(\x0b\x32\x13.dcs.common.v0.Unit2[\n\x0cGroupService\x12K\n\x08GetUnits\x12\x1d.dcs.group.v0.GetUnitsRequest\x1a\x1e.dcs.group.v0.GetUnitsResponse\"\x00\x42OZ,github.com/DCS-gRPC/go-bindings/dcs/v0/group\xaa\x02\x1eRurouniJones.Dcs.Grpc.V0.Groupb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dcs.group.v0.group_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z,github.com/DCS-gRPC/go-bindings/dcs/v0/group\252\002\036RurouniJones.Dcs.Grpc.V0.Group'
  _globals['_GETUNITSREQUEST']._serialized_start=70
  _globals['_GETUNITSREQUEST']._serialized_end=139
  _globals['_GETUNITSRESPONSE']._serialized_start=141
  _globals['_GETUNITSRESPONSE']._serialized_end=195
  _globals['_GROUPSERVICE']._serialized_start=197
  _globals['_GROUPSERVICE']._serialized_end=288
# @@protoc_insertion_point(module_scope)
