# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from dcs.unit.v0 import unit_pb2 as dcs_dot_unit_dot_v0_dot_unit__pb2


class UnitServiceStub(object):
    """https://wiki.hoggitworld.com/view/DCS_Class_Unit
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRadar = channel.unary_unary(
                '/dcs.unit.v0.UnitService/GetRadar',
                request_serializer=dcs_dot_unit_dot_v0_dot_unit__pb2.GetRadarRequest.SerializeToString,
                response_deserializer=dcs_dot_unit_dot_v0_dot_unit__pb2.GetRadarResponse.FromString,
                )
        self.GetPosition = channel.unary_unary(
                '/dcs.unit.v0.UnitService/GetPosition',
                request_serializer=dcs_dot_unit_dot_v0_dot_unit__pb2.GetPositionRequest.SerializeToString,
                response_deserializer=dcs_dot_unit_dot_v0_dot_unit__pb2.GetPositionResponse.FromString,
                )
        self.GetPlayerName = channel.unary_unary(
                '/dcs.unit.v0.UnitService/GetPlayerName',
                request_serializer=dcs_dot_unit_dot_v0_dot_unit__pb2.GetPlayerNameRequest.SerializeToString,
                response_deserializer=dcs_dot_unit_dot_v0_dot_unit__pb2.GetPlayerNameResponse.FromString,
                )
        self.GetDescriptor = channel.unary_unary(
                '/dcs.unit.v0.UnitService/GetDescriptor',
                request_serializer=dcs_dot_unit_dot_v0_dot_unit__pb2.GetDescriptorRequest.SerializeToString,
                response_deserializer=dcs_dot_unit_dot_v0_dot_unit__pb2.GetDescriptorResponse.FromString,
                )
        self.SetEmission = channel.unary_unary(
                '/dcs.unit.v0.UnitService/SetEmission',
                request_serializer=dcs_dot_unit_dot_v0_dot_unit__pb2.SetEmissionRequest.SerializeToString,
                response_deserializer=dcs_dot_unit_dot_v0_dot_unit__pb2.SetEmissionResponse.FromString,
                )
        self.Get = channel.unary_unary(
                '/dcs.unit.v0.UnitService/Get',
                request_serializer=dcs_dot_unit_dot_v0_dot_unit__pb2.GetRequest.SerializeToString,
                response_deserializer=dcs_dot_unit_dot_v0_dot_unit__pb2.GetResponse.FromString,
                )
        self.GetTransform = channel.unary_unary(
                '/dcs.unit.v0.UnitService/GetTransform',
                request_serializer=dcs_dot_unit_dot_v0_dot_unit__pb2.GetTransformRequest.SerializeToString,
                response_deserializer=dcs_dot_unit_dot_v0_dot_unit__pb2.GetTransformResponse.FromString,
                )


class UnitServiceServicer(object):
    """https://wiki.hoggitworld.com/view/DCS_Class_Unit
    """

    def GetRadar(self, request, context):
        """https://wiki.hoggitworld.com/view/DCS_func_getRadar
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPosition(self, request, context):
        """https://wiki.hoggitworld.com/view/DCS_func_getPoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlayerName(self, request, context):
        """https://wiki.hoggitworld.com/view/DCS_func_getPlayerName
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDescriptor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetEmission(self, request, context):
        """https://wiki.hoggitworld.com/view/DCS_func_enableEmission
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """https://wiki.hoggitworld.com/view/DCS_func_getByName
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransform(self, request, context):
        """*
        Get information about the unit in 3D space, including its position,
        orientation and velocity.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UnitServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRadar': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRadar,
                    request_deserializer=dcs_dot_unit_dot_v0_dot_unit__pb2.GetRadarRequest.FromString,
                    response_serializer=dcs_dot_unit_dot_v0_dot_unit__pb2.GetRadarResponse.SerializeToString,
            ),
            'GetPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPosition,
                    request_deserializer=dcs_dot_unit_dot_v0_dot_unit__pb2.GetPositionRequest.FromString,
                    response_serializer=dcs_dot_unit_dot_v0_dot_unit__pb2.GetPositionResponse.SerializeToString,
            ),
            'GetPlayerName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlayerName,
                    request_deserializer=dcs_dot_unit_dot_v0_dot_unit__pb2.GetPlayerNameRequest.FromString,
                    response_serializer=dcs_dot_unit_dot_v0_dot_unit__pb2.GetPlayerNameResponse.SerializeToString,
            ),
            'GetDescriptor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDescriptor,
                    request_deserializer=dcs_dot_unit_dot_v0_dot_unit__pb2.GetDescriptorRequest.FromString,
                    response_serializer=dcs_dot_unit_dot_v0_dot_unit__pb2.GetDescriptorResponse.SerializeToString,
            ),
            'SetEmission': grpc.unary_unary_rpc_method_handler(
                    servicer.SetEmission,
                    request_deserializer=dcs_dot_unit_dot_v0_dot_unit__pb2.SetEmissionRequest.FromString,
                    response_serializer=dcs_dot_unit_dot_v0_dot_unit__pb2.SetEmissionResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=dcs_dot_unit_dot_v0_dot_unit__pb2.GetRequest.FromString,
                    response_serializer=dcs_dot_unit_dot_v0_dot_unit__pb2.GetResponse.SerializeToString,
            ),
            'GetTransform': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransform,
                    request_deserializer=dcs_dot_unit_dot_v0_dot_unit__pb2.GetTransformRequest.FromString,
                    response_serializer=dcs_dot_unit_dot_v0_dot_unit__pb2.GetTransformResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dcs.unit.v0.UnitService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UnitService(object):
    """https://wiki.hoggitworld.com/view/DCS_Class_Unit
    """

    @staticmethod
    def GetRadar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dcs.unit.v0.UnitService/GetRadar',
            dcs_dot_unit_dot_v0_dot_unit__pb2.GetRadarRequest.SerializeToString,
            dcs_dot_unit_dot_v0_dot_unit__pb2.GetRadarResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dcs.unit.v0.UnitService/GetPosition',
            dcs_dot_unit_dot_v0_dot_unit__pb2.GetPositionRequest.SerializeToString,
            dcs_dot_unit_dot_v0_dot_unit__pb2.GetPositionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPlayerName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dcs.unit.v0.UnitService/GetPlayerName',
            dcs_dot_unit_dot_v0_dot_unit__pb2.GetPlayerNameRequest.SerializeToString,
            dcs_dot_unit_dot_v0_dot_unit__pb2.GetPlayerNameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDescriptor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dcs.unit.v0.UnitService/GetDescriptor',
            dcs_dot_unit_dot_v0_dot_unit__pb2.GetDescriptorRequest.SerializeToString,
            dcs_dot_unit_dot_v0_dot_unit__pb2.GetDescriptorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetEmission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dcs.unit.v0.UnitService/SetEmission',
            dcs_dot_unit_dot_v0_dot_unit__pb2.SetEmissionRequest.SerializeToString,
            dcs_dot_unit_dot_v0_dot_unit__pb2.SetEmissionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dcs.unit.v0.UnitService/Get',
            dcs_dot_unit_dot_v0_dot_unit__pb2.GetRequest.SerializeToString,
            dcs_dot_unit_dot_v0_dot_unit__pb2.GetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTransform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dcs.unit.v0.UnitService/GetTransform',
            dcs_dot_unit_dot_v0_dot_unit__pb2.GetTransformRequest.SerializeToString,
            dcs_dot_unit_dot_v0_dot_unit__pb2.GetTransformResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
