# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dcs/controller/v0/controller.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"dcs/controller/v0/controller.proto\x12\x11\x64\x63s.controller.v0\"\xff\x01\n\x14SetAlarmStateRequest\x12\x14\n\ngroup_name\x18\x01 \x01(\tH\x00\x12\x13\n\tunit_name\x18\x02 \x01(\tH\x00\x12G\n\x0b\x61larm_state\x18\x03 \x01(\x0e\x32\x32.dcs.controller.v0.SetAlarmStateRequest.AlarmState\"k\n\nAlarmState\x12\x1b\n\x17\x41LARM_STATE_UNSPECIFIED\x10\x00\x12\x14\n\x10\x41LARM_STATE_AUTO\x10\x01\x12\x15\n\x11\x41LARM_STATE_GREEN\x10\x02\x12\x13\n\x0f\x41LARM_STATE_RED\x10\x03\x42\x06\n\x04name\"\x17\n\x15SetAlarmStateResponse2y\n\x11\x43ontrollerService\x12\x64\n\rSetAlarmState\x12\'.dcs.controller.v0.SetAlarmStateRequest\x1a(.dcs.controller.v0.SetAlarmStateResponse\"\x00\x42YZ1github.com/DCS-gRPC/go-bindings/dcs/v0/controller\xaa\x02#RurouniJones.Dcs.Grpc.V0.Controllerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dcs.controller.v0.controller_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z1github.com/DCS-gRPC/go-bindings/dcs/v0/controller\252\002#RurouniJones.Dcs.Grpc.V0.Controller'
  _globals['_SETALARMSTATEREQUEST']._serialized_start=58
  _globals['_SETALARMSTATEREQUEST']._serialized_end=313
  _globals['_SETALARMSTATEREQUEST_ALARMSTATE']._serialized_start=198
  _globals['_SETALARMSTATEREQUEST_ALARMSTATE']._serialized_end=305
  _globals['_SETALARMSTATERESPONSE']._serialized_start=315
  _globals['_SETALARMSTATERESPONSE']._serialized_end=338
  _globals['_CONTROLLERSERVICE']._serialized_start=340
  _globals['_CONTROLLERSERVICE']._serialized_end=461
# @@protoc_insertion_point(module_scope)
